[package]
edition = "2021"
name = "lapce-lua"
version = "0.0.1"

[dependencies]
flate2 = "1.0.22"
lapce-plugin = "0.1.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.59"
zip = {version = "0.6.0", default-features = false, features = ["deflate"]}
